In [1]:
import pandas as pd

In [3]:
files = {
    "sales_validation": "sales_train_validation.csv",
    "sales_evaluation": "sales_train_evaluation.csv",
    "calendar": "calendar.csv",
    "prices": "sell_prices.csv",
}

dfs = {}

for name, path in files.items():
    df = pd.read_csv(path)
    dfs[name] = df
    
    print(f"\n{name}")
    print("shape:", df.shape)
    print("memory MB:", round(df.memory_usage(deep=True).sum() / 1024**2, 2))
    display(df.head())

sales_validation
shape: (30490, 1919)
memory MB: 455.38

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1904,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,3,0,1,1,1,3,0,1,1
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,1,2,1,1,1,0,1,1,1
3,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,0,5,4,1,0,1,3,7,2
4,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,1,1,0,1,1,2,2,2,4

sales_evaluation
shape: (30490, 1947)
memory MB: 461.9

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1932,d_1933,d_1934,d_1935,d_1936,d_1937,d_1938,d_1939,d_1940,d_1941
0,HOBBIES_1_001_CA_1_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,4,0,0,0,0,3,3,0,1
1,HOBBIES_1_002_CA_1_evaluation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,1,2,1,1,0,0,0,0,0
2,HOBBIES_1_003_CA_1_evaluation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,0,2,0,0,0,2,3,0,1
3,HOBBIES_1_004_CA_1_evaluation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,1,0,4,0,1,3,0,2,6
4,HOBBIES_1_005_CA_1_evaluation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,0,0,2,1,0,0,2,1,0

calendar
shape: (1969, 14)
memory MB: 0.67

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,2011-01-29,11101,Saturday,1,1,2011,d_1,NaN,NaN,NaN,NaN,0,0,0
1,2011-01-30,11101,Sunday,2,1,2011,d_2,NaN,NaN,NaN,NaN,0,0,0
2,2011-01-31,11101,Monday,3,1,2011,d_3,NaN,NaN,NaN,NaN,0,0,0
3,2011-02-01,11101,Tuesday,4,2,2011,d_4,NaN,NaN,NaN,NaN,1,1,0
4,2011-02-02,11101,Wednesday,5,2,2011,d_5,NaN,NaN,NaN,NaN,1,0,1

prices
shape: (6841121, 4)
memory MB: 853.13

  store_id        item_id  wm_yr_wk  sell_price
0     CA_1  HOBBIES_1_001     11325        9.58
1     CA_1  HOBBIES_1_001     11326        9.58
2     CA_1  HOBBIES_1_001     11327        8.26
3     CA_1  HOBBIES_1_001     11328        8.26
4     CA_1  HOBBIES_1_001     11329        8.26

In [4]:
for name, df in dfs.items():
    print(f"\n--- {name} ---")
    print(df.dtypes)

--- sales_validation ---
id          object
item_id     object
dept_id     object
cat_id      object
store_id    object
             ...
d_1909       int64
d_1910       int64
d_1911       int64
d_1912       int64
d_1913       int64
Length: 1919, dtype: object

--- sales_evaluation ---
id          object
item_id     object
dept_id     object
cat_id      object
store_id    object
             ...
d_1937       int64
d_1938       int64
d_1939       int64
d_1940       int64
d_1941       int64
Length: 1947, dtype: object

--- calendar ---
date            object
wm_yr_wk         int64
weekday         object
wday             int64
month            int64
year             int64
d               object
event_name_1    object
event_type_1    object
event_name_2    object
event_type_2    object
snap_CA          int64
snap_TX          int64
snap_WI          int64
dtype: object

--- prices ---
store_id       object
item_id        object
wm_yr_wk        int64
sell_price    float64
dtype: object

In [5]:
for name, df in dfs.items():
    print(f"\n--- {name} missing values ---")
    
    missing = (
        df.isna()
        .sum()
        .sort_values(ascending=False)
    )
    
    display(missing[missing > 0].head(20))

--- sales_validation missing values ---

Series([], dtype: int64)

--- sales_evaluation missing values ---

Series([], dtype: int64)

--- calendar missing values ---

event_name_2    1964
event_type_2    1964
event_name_1    1807
event_type_1    1807
dtype: int64

--- prices missing values ---

Series([], dtype: int64)

sales_validation duplicate rows: 0
sales_evaluation duplicate rows: 0
calendar duplicate rows: 0
prices duplicate rows: 0

In [7]:
sales = dfs["sales_evaluation"]

print("stores:", sales["store_id"].nunique())
print("items:", sales["item_id"].nunique())
print("departments:", sales["dept_id"].nunique())
print("categories:", sales["cat_id"].nunique())
print("states:", sales["state_id"].unique())

print("\nStores:")
print(sales["store_id"].value_counts())

stores: 10
items: 3049
departments: 7
categories: 3
states: ['CA' 'TX' 'WI']

Stores:
store_id
CA_1    3049
CA_2    3049
CA_3    3049
CA_4    3049
TX_1    3049
TX_2    3049
TX_3    3049
WI_1    3049
WI_2    3049
WI_3    3049
Name: count, dtype: int64

In [8]:
day_cols = [c for c in sales.columns if c.startswith("d_")]

print("number of sales days:", len(day_cols))
print("first:", day_cols[:5])
print("last:", day_cols[-5:])

number of sales days: 1941
first: ['d_1', 'd_2', 'd_3', 'd_4', 'd_5']
last: ['d_1937', 'd_1938', 'd_1939', 'd_1940', 'd_1941']

In [10]:
calendar = dfs["calendar"]
sales = dfs["sales_evaluation"]
prices = dfs["prices"]

calendar["date"] = pd.to_datetime(calendar["date"])

In [11]:
print(calendar["date"].dtype)
print(calendar["date"].min())
print(calendar["date"].max())

datetime64[ns]
2011-01-29 00:00:00
2016-06-19 00:00:00

In [13]:
sales = dfs["sales_evaluation"].copy()
calendar = dfs["calendar"].copy()
prices = dfs["prices"].copy()

In [14]:
categorical_cols = [
    "item_id", "dept_id", "cat_id",
    "store_id", "state_id"
]

for col in categorical_cols:
    sales[col] = sales[col].astype("category")

In [16]:
calendar = dfs["calendar"].copy()
calendar["date"] = pd.to_datetime(calendar["date"])

calendar.to_csv(
    "calendar_clean.csv",
    index=False
)

In [19]:
import pandas as pd

sales = pd.read_csv("sales_train_evaluation.csv")

sales.to_parquet(
    "sales_train_evaluation.parquet",
    engine="pyarrow",
    compression="snappy",
    index=False
)